configure.ac: Skip -I for RAPIDCHECK_HEADERS when not set
I was seeing build output which looked like:

g++ -o src/libcmd/repl.o -c src/libcmd/repl.cc <snip> -I src -I -DREADLINE <snip>
src/libcmd/repl.cc:18:10: fatal error: editline.h: No such file or directory
   18 | #include <editline.h>
      |          ^~~~~~~~~~~~
compilation terminated.

Notice the second -I is not followed by a path. I think this caused
the -DREADLINE to be interpreted as the path, and therefore the
READLINE macro wasn't defined. This lead to the incorrect
pre-processing of src/libcmd/repl.cc.

I did not test the case where the RAPIDCHECK_HEADERS variable was set.

Signed-off-by: Jordan Justen <jljusten@gmail.com>
Forwarded: https://github.com/NixOS/nix/pull/8757